# As many as wanted
web2:
  build: node/
  external_links:
    # Make all proxy-admin instances available through the proxy as proxy-admin.infra
    - "load-balancer:proxy-admin.infra"
    # Make all consul-admin instances available through the proxy as consul-admin.infra
    - "load-balancer:consul-admin.infra"
  environment:
    SERVICE_NAME: 'www'
    SERVICE_CHECK_HTTP: '/'
    SERVICE_CHECK_INTERVAL: '5s'
    SERVICE_TAGS: 'sticky_session,public_ipaddress=128.1.2.3,server_alias=www.127.0.0.1.xip.io'
  ports:
    - 80
